### ISSUE TITLE
Directory names unification

### ISSUE THREAD

**Issue by vizh** [yiisoft/yii-base-web#12]
Every directory in project's root is in singular form, but the tests folder in plural. I think it would be nice to resolve this issue before the release. I can prepare a pull request if you think it's a problem too.

**Comment by schmunk42** [comment]
`tests` would be fine for me, was also discussed here: https://github.com/yiisoft/yii2-app/issues/2

It the most common naming AFAIK; `srcs`, `configs` would not make sense.

**Comment by samdark** [comment]
These are common names. Won't change it.
