### ISSUE TITLE
Split сonfig web|console.php to small files

### ISSUE THREAD

**Issue by exileed** [yiisoft/yii-base-web#17]
Split bit сonfig file (web|console.php) to small config (cache.php, logger.php ect...)
Small file edit more convenient. 
Each file is responsible for one component. You can quickly find the required configs.

Example https://github.com/exileed/yii2-app/tree/feature/small-config/config

**Comment by samdark** [comment]
Yes, could be done. Would you like to send a pull request?

**Comment by schmunk42** [comment]
@samdark I don't really favour such a change, since it's harder to find a certain piece of configuration.
I'd prefer a very minimal config for the application template.

**Comment by samdark** [comment]
What do you mean by "harder to find a certain piece of configuration"? Any example of what would be harder to find in this case?

**Comment by schmunk42** [comment]
In the example above there's ie. the database config read into `$db`, some other configs are required directly, but `i18n` is part of the `web.php` - there's no convention when to use require or a variable.

If I am looking for the cache configuraton I also need to look if it's also included in web and/or console. The more files you have the more logic is required to merge them. And there's currently no way to retrieve the merged configs *from the application*.

I'd rather prefer to split configs depending on `YII_ENV` and `YII_DEBUG`, than by component or module.

**Comment by schmunk42** [comment]
I'd find a `common.php` much more imporant. It would reduce the amout of duplicated config a lot.

```
_db.php
_urls.php
common.php
console.php
messages.php
web.php
```

When using sub-configs they should be indicated by some convetions, ie. `_` dot-notation or even a subfolder `components` and/or `modules`.

```
components.db.php
components/db.php

components.urlManager.rules.php
```

**Comment by omzy** [comment]
Use Laravel's config structure as an example:

https://github.com/laravel/laravel/tree/master/config

Combined with `.env` file it is super simple to adjust config settings. I really don't like putting the actual  values in the config files themselves and then doing `if (YII_ENV_DEV)` everywhere..

**Comment by schmunk42** [comment]
We're using conventions to add `-web` or `-debug` to the config files, but it requires some logic to merge them: https://github.com/dmstr/phd5-app/blob/master/src/config/main.php

**Comment by allyraza** [comment]
everybody want a structure similar to laravel what I don't understand why don't you guys use laravel no offense it is great tool, if you are a yii user then own it I believe yii's current config structure is great and works for most cases although you have the flexibility to change how you like it.
