### ISSUE TITLE
Could not find package yiisoft/yii2-app with stability dev.

### ISSUE THREAD

**Issue by marcelodeandrade** [yiisoft/yii-base-web#18]
### What steps will reproduce the problem?

`composer create-project --prefer-dist --stability=dev yiisoft/yii2-app myapp`

### What's expected?

Create a new project with Yii 2.1

### What do you get instead?

> [InvalidArgumentException]                                   
>   Could not find package yiisoft/yii2-app with stability dev.
> 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.1
| PHP version      | 7.2
| Operating system | Ubuntu 16.04

**Comment by samdark** [comment]
Fixed.
