### ISSUE TITLE
Aliases are broken

### ISSUE THREAD

**Issue by exileed** [yiisoft/yii-base-web#19]
Aliases are broken.
Example :
`@vendor` -> `src/vendor`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.1.x-dev
| PHP version      | 7.2
| Operating system | *nix

**Comment by dabagab** [comment]
Yii-Asset, Yii-Captcha extensions are referenced to the `@yii` alias instead of the `@yii-asset `or `@yii-captcha.`
