### ISSUE TITLE
Invalid Configuration User::identityClass must be set.

### ISSUE THREAD

**Issue by kids-return** [yiisoft/yii-base-web#25]
is need create /src/models/User.php ?
or
remove views/*  \Yii::$app->user ?

**Comment by marcelodeandrade** [comment]
You only need set the [User identity](https://www.yiiframework.com/doc/api/2.0/yii-web-user) in your config components: 
```
components => [
    ...,
    'user' => [
         'identityClass' => 'app\models\User', // User must implement the IdentityInterface
    ]
]
```

**Comment by kids-return** [comment]
all right.
The project did not create `app\models\User`.
need add  `app\models\User` file

**Comment by kids-return** [comment]
I intend to fix the bug of this project recently.
make it work.
