### ISSUE TITLE
Versioning of project versions

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii-base-web#3]
The template should introduce a proper versioning workflow, which allows the developer to easily get/set/create/update the current version of the project.

*Our* current approach:

```
version:
	$(shell echo $(shell git describe --long --tags --dirty --always) > ../src/version)
	@echo $(shell cat ../src/version)
```

For reference: [PHP helper for versions](https://github.com/sebastianbergmann/version)

This could also be "the feature" of an initial CLI command, `yii app/version`.

**Comment by samdark** [comment]
What's the use case?

**Comment by schmunk42** [comment]
When accessing an application I want to be 100% sure which version is running, sometimes an update might have failed or source-code is distributed (scaled) across multiple systems.

Like every program has a `--version` option.

**Comment by samdark** [comment]
Looks out of Yii scope to me. Also, one could use mercurial or even SVN or, far worse, CVS :)

**Comment by klimov-paul** [comment]
Version can be easily maintained since:
https://github.com/yiisoft/yii2/pull/12727

But actual version detection is too application specific. See following for example:
https://github.com/yiisoft/yii2/pull/12727#discussion_r82987297
