### ISSUE TITLE
Directory Models and Forms.

### ISSUE THREAD

**Issue by tecnoterabyte** [yiisoft/yii-base-web#33]
I'm somewhat confused, as I understood the models would be in forms such as LoginForm and ContacForm, because not to put the model User in the forms directory, or simply move all models to models, it would be important to have it clearly defined.

**Comment by samdark** [comment]
form models are in `forms`, other models are in `models`

**Comment by rob006** [comment]
If they're "form models" shouldn't we put them into `models/forms`?

**Comment by samdark** [comment]
We can, yes. It's up to personal taste.
