### ISSUE TITLE
(feat) backend/ frontend setup for docs

### ISSUE THREAD

**Issue by axtho** [yiisoft/yii-base-web#36]
### What steps will reproduce the problem?
Using the app, as is, will not easily give you a backend/ frontend setup.

### What's expected?
Previously there were advanced templates that solved the backend/ frontend issue.
It would be great if this one template could make such a setup possible without the need for advanced templates.

Was there something like this planned?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.1.x-dev
| PHP version      |7.2.1
| Operating system | OSX

**Comment by samdark** [comment]
No, it is a single entry app. Admin part could be implemented as a module. Alternatively, you can create advanced-like app yourself.
