### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by ShNURoK42** [yiisoft/yii-base-web#44]
Try to install app with command `composer create-project --prefer-dist --stability=dev yiisoft/app myapp`.

App installs, but failed dependency of yii core.

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/core 3.0.x-dev requires psr/container-implementation ^1.0 -> no matching package found.
    - yiisoft/yii2-jquery 1.0.x-dev requires yiisoft/core ^3.0@dev -> satisfiable by yiisoft/core[3.0.x-dev].
    - Installation request for yiisoft/yii2-jquery 1.0.x-dev -> satisfiable by yiisoft/yii2-jquery[1.0.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

```

**Comment by hiqsol** [comment]
Thank you for the report.
I'll check it up myself and give you more information.

**Comment by hiqsol** [comment]
Application architecture is changed.
Now application template is [yiisoft/yii-app-template](https://github.com/yiisoft/yii-app-template).
You can install it with the same `composer create-project` command.
The application is working but layout is broken.

Sorry, no actual docs at the moment.
But you can read this article https://hiqdev.com/pages/articles/app-organization

**Comment by Shutclare** [comment]
it will installed if you delete --prefer-dist
but will appear the bug with "beforeAction"  https://github.com/yiisoft/yii-console/pull/1

**Comment by hiqsol** [comment]
Should work now (but remember - layout is broken, fixing now).
If not, please show errors.
