### ISSUE TITLE
Rename repo to yii-base-web

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii-base-web#45]
### What steps will reproduce the problem?

Create an app/project from this repo

### What's expected?

To get an app (since it's in the name)

### What do you get instead?

A (non-working) module ;) See also https://github.com/yiisoft/yii-app/issues/40#issuecomment-415016834

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 3.0
| PHP version      | any 
| Operating system | any

**Comment by hiqsol** [comment]
I have more arguments to call it application.
Maybe better something like 'application base', I can't find good english name.

Application is different from module that while having same functions it has different positioning.
If we compare a big project to a tree ... :)
The `yii-app` is like a trunk and modules are like branches. And `yii-app-template` is like a root which connects the tree to the ground (application to the server).

So the definition and rule of thumb is: modules are connected to apps, apps incorporate modules.
I think in this sense `yii-app` is application, not a module.

But I agree it is discussable.
So I ask @samdark, @cebe, @SilverFire to tell what they think about the question.

**Comment by marcelodeandrade** [comment]
So what do you mean is `yii-app` will be acting like a "core module" to connect other modules like [cache](https://github.com/yiisoft/cache), [log](https://github.com/yiisoft/log), [db](https://github.com/yiisoft/db), [di](https://github.com/yiisoft/di), etc... and finish a functional app to serve in a `yii-app-template`? 

If i'm correct, that changes should be clear in [ROADMAP](https://github.com/yiisoft/yii2/blob/master/ROADMAP.md), or any docs, avoiding mistakes when new developers come to yii 3.x

**Comment by hiqsol** [comment]
I thought more about the question.
It's the question of naming. And good naming is for easier explanation and better understanding.
I'm afraid that it's more difficult to explain why we have several applications in our application and why we include application into application ;)
So, I agree better call it module. It is natural to have multiple modules in application.

But I'm not sure about `yii-web-module`.
Thinking if we can find a better name.
Please propose your variants.

`yii-web-base`, `yii-module-base`, ...

And what should be recommended naming style for modules:
`yii-module-something`
`yii-something-module`
else?

**Comment by schmunk42** [comment]
> I'm afraid that it's more difficult to explain why we have several applications in our application and why we include application into application ;)

OK, so let's switch sides in the argumentation :) 

First, let's assume the current repo `yii-app-template` is named `project-template` (no PHP at all :+1:)
We could then add applications to it, there are already 2-3 types (Web/API, CLI)

    composer require yiisoft/app-web yiisoft/app-api yiisoft/app-cli yiisoft/app-vue

For sure you can also use just one or any other combinaton, this relates closely to https://github.com/yiisoft/app-api/issues/1

**Comment by hiqsol** [comment]
@schmunk42 Good idea too :)

So we have root package called "project" and it includes "application" (or maybe even applications).

Ok. Now we have good variants and arguments. Let's wait for others to say.

**Comment by hiqsol** [comment]
After discussion in yii team we've come to this naming style:

- `yii-project-template` - Yii Framework Project Template (to be renamed from `yii-app-template`)
- `yii-base-web` - Yii Framework Web Application Base (to be renamed from `yii-app`)
- `yii-base-api` - Yii Framework API Application Base (to be renamed from `app-api`)
- `yii-base-cli` - Yii Framework CLI Application Base

And general naming convention for yii extensions: `yii-type-something`:

- application bases: `yii-base-web`, `yii-base-api`, ...
- modules: `yii-module-users`, `yii-module-pages`, ...
- themes: `yii-theme-adminlte`, `yii-theme-hyde`, ...
- widgets: `yii-widget-datepicker`, ...
- and so on

**Comment by hiqsol** [comment]
The renaming will be done soon.
Also `yiisoft/core` will be renamed `yiisoft/yii-core` to follow general naming convention for distinguishing Yii Libraries from Yii Framework.
Here you can see the agreements and list of packages https://github.com/yiisoft/docs/blob/master/packages.md

**Comment by schmunk42** [comment]
I'd move the Yii Framework part above Libraries https://github.com/yiisoft/docs/blob/master/packages.md#yii-framework - it's the most important part.

Could be:
- Yii Framework
- Yii project template and application bases
- Standalone Libraries
- ...

**Comment by tecnoterabyte** [comment]
yii-app --> application base
yii-web-app-template --> Yii Framework Web Project Template

**Comment by SilverFire** [comment]
Renamed to `yii-base-web`

**Comment by schmunk42** [comment]
What‘s about the user & login part?
I‘d like to see it in a separate module or even a third-party one like usuario.

**Comment by hiqsol** [comment]
> What‘s about the user & login part?
> I‘d like to see it in a separate module or even a third-party one like usuario.

Ok. I'm afraid we can't get final decision now.
I'm all for separate solutions.
Maybe let's see them and then we decide.

**Comment by kids-return** [comment]
need create `yii-base-cli` repo

**Comment by schmunk42** [comment]
@samdark @cebe Could you create the CLI repo?

**Comment by samdark** [comment]
Done.
