### ISSUE TITLE
Running app on docker cause connection timeout

### ISSUE THREAD

**Issue by marcelodeandrade** [yiisoft/yii-base-web#49]
### What steps will reproduce the problem?

Create a new app following [installation](https://github.com/yiisoft/yii-base-web/blob/master/README.md#installation) and run on docker

### What's expected?

Running app on docker

### What do you get instead?
```

This site can’t be reached docker.host took too long to respond.
Search Google for docker host 30080
ERR_CONNECTION_TIMED_OUT

```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | ^3.0@dev
| PHP version      | x
| Operating system | x

**Comment by schmunk42** [comment]
What's the IP of your `docker.host`?  Looks like your DNS can not resolve it.

---

@samdark I think this repo should not contain Docker support anymore, since it should be installed into a project template which handles that.

We might use Docker for testing though, which could serve as an example.

**Comment by samdark** [comment]
@hiqsol?

**Comment by marcelodeandrade** [comment]
> What's the IP of your `docker.host`? Looks like your DNS can not resolve it.

```
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS  PORTS                   NAMES
79fa340cc6f9        yiisoftware/yii2-php:7.2-apache   "docker-php-entrypoi…"   23 seconds ago      Up 18 seconds  0.0.0.0:30080->80/tcp   yiibaseweb_php_1
```

I can access with `http://0.0.0.0:30080` in browser

**Comment by schmunk42** [comment]
Which OS do you use, along with which Docker implementation (Docker for Mac/Win, docker-machine, ...)?

**Comment by marcelodeandrade** [comment]
Ubuntu 18.04 with 

```
docker-ce/bionic,now 18.06.1~ce~3-0~ubuntu amd64 [installed]
docker-compose/bionic,bionic,now 1.17.1-2 all [installed]
```

**Comment by hiqsol** [comment]
> I think this repo should not contain Docker support anymore since it should be installed into a project template which handles that.

@schmunk42 Agree with clarification.
This package is the library now. And generally speaking, the library can and should provide anything needed to use the library with Docker.
Speaking in detail example `docker-compose.yml` should be in the template package.
But anything reusable between projects should be here.
