### ISSUE TITLE
where is the index.php file

### ISSUE THREAD

**Issue by allyraza** [yiisoft/yii-base-web#53]
### What steps will reproduce the problem?
composer create-project --prefer-dist --stability=dev yiisoft/app myapp

### What's expected?
an index.php file public

### What do you get instead?
no index.php in public

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 3
| PHP version      | 7.2
| Operating system | macos

**Comment by hiqsol** [comment]
Example index.php is in the yii-project-template package.

**Comment by schmunk42** [comment]
But it would be the right thing, if the `index.php` according with the webserver config is moved to this repo.
A project could be an API on a different port and with a CLI base, it might not have an `index.php`.
