### ISSUE TITLE
Do we need to require yii-console?

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii-base-web#58]
### What steps will reproduce the problem?

Install this application base

### What's expected?

I'd expect to get `yii-console` only for `yii-base-cli`.

### What do you get instead?

It's installed because of https://github.com/yiisoft/yii-base-web/blob/master/composer.json#L30

**Comment by schmasterz** [comment]
Most likely yii-base-web does not require yii-console, but active-record is required dependency by yii-base-web . Don't forget that  yii-console contains  MigrateController.
My suggestion is to remove yii-console from yii-base-web and add it as required to active-record.

**Comment by schmasterz** [comment]
Sorry.
yii-web which is required by yii-base-web requires  yiisoft/yii-core, and yii-core requires yii-console. So probably there is no need to require yii-console in yii-base-web :)

**Comment by samdark** [comment]
No.

**Comment by schmunk42** [comment]
Fixed in https://github.com/yiisoft/yii-base-web/commit/49803cdae672f1ae2bebd0e0fc763606081f9ddb
