### ISSUE TITLE
Question: how to configure db

### ISSUE THREAD

**Issue by np25071984** [yiisoft/yii-base-web#64]
Newly created Yii3 project. All I want is just setup db-connection, but I can't understand where is the config file and what is its syntax. How to configure the unit tests to work with databases?

```
composer create-project --prefer-dist --stability=dev yiisoft/yii-project-template myapp
cd myapp
ls config/
common.php  params.php
```

It seems like the application doesn't read `params.php` file at all (I even made syntax error and didn't get any notices about it).

**Comment by schmunk42** [comment]
See https://github.com/yiisoft/yii-project-template#configuration

**Comment by np25071984** [comment]
But it doesn't help me...

```
$ cat config/params.php 
<?php

return [
    'i18n.locale' => 'en-US',
    'debug.allowedIPs' => ['127.0.0.1'],

    'db.dsn'        => 'mysql:host=127.0.0.1;dbname=demo',
    'db.name'       => 'yii2',
    'db.host'       => '127.0.0.1',
    'db.user'       => 'yii2',
    'db.password'   => 'yii2pass',
];
```

I still get wrong data inside `yii\db\Connection` object.

**Comment by schmunk42** [comment]
Did you run `composer du` to update the generated config?

**Comment by np25071984** [comment]
> Did you run `composer du` to update the generated config?

Thank you! Now it works fine

**Comment by schmunk42** [comment]
Related: https://github.com/machour/yii3-kitchen-sink

**Comment by np25071984** [comment]
@schmunk42 Sorry, but one more silly question - how to configure test env?
```
$ cd vendor/yiisoft/yii-core
$ cat config/tests.php 
<?php

$_ENV['TEST_RUNTIME_PATH'] = $_ENV['TEST_RUNTIME_PATH'] ?? dirname(__DIR__) . '/runtime';

return [
    'app' => [
        'id' => 'testapp',
    ],
    'aliases' => [
        '@runtime'           => $_ENV['TEST_RUNTIME_PATH'],
    ],
];
```

Where I should put all the db connection configs?

**Comment by schmunk42** [comment]
You should be able to put your db config into `tests.php`, but `$_ENV` support is missing or let's say ENV vars are evaluated. See also https://github.com/hiqdev/composer-config-plugin/issues/11

CC @hiqsol If you have some input on this, please let us know.
