### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-base-web#8]
Should be considered but since there are problems running containers natively under Windows and MacOS it may make sense to still run it in Vagrant container...

See basic app and https://github.com/yiisoft/yii2-app-advanced/pull/250

**Comment by schmunk42** [comment]
I'd actually recommend Docker-for-Mac for OS X at the moment. I ran that for a few months now and had less problems than with VMs.

Mac users should consult https://docs.docker.com/docker-for-mac/osxfs-caching/ to get a decent filessytem performance.

For reference, several devs of our company are also using this Vagrant Docker setup with NFS mounts https://github.com/dmstr/vado-ligure

**Comment by schmunk42** [comment]
continued from https://github.com/yiisoft/yii-base-web/issues/8

I think this repo should provide the required configurations for Apache and nginx (also) when running with Docker. These should be integrated into the `yii2-project-template` environment upon installation, but we need to figure out a nice way to do so.

**Comment by schmunk42** [comment]
Closing this, since Docker and Vagrant support should be done in https://github.com/yiisoft/yii-project-template
